USE bytehub;

UPDATE products SET specifications = 'Specification|Details\n---|---\nTotal Cores|24\n# of Performance-cores|8\n# of Efficient-cores|16\nTotal Threads|32\nMax Turbo Frequency|5.80 GHz\nIntel® Thermal Velocity Boost Frequency|5.80 GHz\nIntel® Turbo Boost Max Technology 3.0 Frequency|5.70 GHz\nPerformance-core Max Turbo Frequency|5.40 GHz\nEfficient-core Max Turbo Frequency|4.30 GHz\nCache|36 MB Intel® Smart Cache\nTotal L2 Cache|32 MB\nProcessor Base Power|125 W\nMaximum Turbo Power|253 W\nMemory Types|Up to DDR5 5600 MT/s, Up to DDR4 3200 MT/s\nMax # of Memory Channels|2\nPCI Express Revision|5.0 and 4.0\nMax # of PCI Express Lanes|20\nSockets Supported|FCLGA1700' WHERE product_name = 'Intel Core i9-13900K';

UPDATE products SET specifications = 'Specification|Details\n---|---\nCPU Cores|16\nCPU Threads|32\nBase Clock|4.5GHz\nMax Boost Clock|Up to 5.7GHz\nTotal L1 Cache|1MB\nTotal L2 Cache|16MB\nTotal L3 Cache|64MB\nUnlocked for Overclocking|Yes\nCMOS|TSMC 5nm FinFET\nPackage|AM5\nPCI Express® Version|PCIe 5.0\nIntegrated Graphics|AMD Radeon™ Graphics\nGraphics Core Count|2\nDefault TDP|170W' WHERE product_name = 'AMD Ryzen 9 7950X';

UPDATE products SET specifications = 'Specification|Details\n---|---\nGPU Engine|Ada Lovelace\nCUDA Cores|16384\nBoost Clock|2.52 GHz\nStandard Memory Config|24 GB GDDR6X\nMemory Interface Width|384-bit\nRay Tracing Cores|3rd Generation\nTensor Cores|4th Generation\nNVIDIA DLSS|3.0\nPCI Express|Gen 4\nOutputs|1x HDMI, 3x DisplayPort\nPower Connectors|1x 16-pin (12VHPWR)\nRecommended PSU|850W' WHERE product_name = 'NVIDIA GeForce RTX 4090';

UPDATE products SET specifications = 'Specification|Details\n---|---\nArchitecture|AMD RDNA™ 3\nStream Processors|6144\nCompute Units|96\nRay Accelerators|96\nGame Clock|2.3 GHz\nBoost Clock|Up to 2.5 GHz\nMemory Size|24 GB GDDR6\nMemory Interface|384-bit\nInfinity Cache|96MB (2nd Gen)\nDisplayPort|2.1\nHDMI|2.1a\nPower Connectors|2x 8-pin\nRecommended PSU|800W' WHERE product_name = 'AMD Radeon RX 7900 XTX';

UPDATE products SET specifications = 'Specification|Details\n---|---\nChipset|Intel® Z790\nCPU Socket|LGA1700\nForm Factor|ATX\nPower Stages|20+1 (90A)\nMemory Support|4x DIMM, Max. 128GB, DDR5\nMax Memory Speed|7800+(OC)\nExpansion Slots|2x PCIe 5.0 x16, 1x PCIe 4.0 x4\nStorage|1x M.2 PCIe 5.0, 4x M.2 PCIe 4.0, 6x SATA 6Gb/s\nNetworking|Intel® 2.5Gb Ethernet, Intel® Wi-Fi 6E\nAudio|ROG SupremeFX 7.1 ALC4082\nRear I/O|2x Thunderbolt™ 4, 6x USB 3.2 Gen 2, 4x USB 3.2 Gen 1, HDMI, Wi-Fi 6E, 2.5Gb LAN, BIOS FlashBack™, Clear CMOS' WHERE product_name = 'ASUS ROG Maximus Z790 Hero';

UPDATE products SET specifications = 'Specification|Details\n---|---\nChipset|AMD X670E\nCPU Socket|AM5\nForm Factor|E-ATX\nPower Phases|22+2+1 Duet Rail (90A)\nMemory Support|4x DIMM, Max. 128GB, DDR5\nMax Memory Speed|6666+(OC)\nExpansion Slots|3x PCIe 5.0 x16\nStorage|1x M.2 PCIe 5.0, 3x M.2 PCIe 4.0, 6x SATA 6Gb/s\nNetworking|Marvell® 10Gbps LAN, Intel® Wi-Fi 6E\nAudio|Realtek® ALC4082 Codec + ESS ES9280AQ Combo DAC/HPA\nRear I/O|Clear CMOS, Flash BIOS, 10G LAN, Wi-Fi 6E, 11x USB 3.2 Gen 2, 1x USB-C 3.2 Gen 2x2' WHERE product_name = 'MSI MEG X670E ACE';

UPDATE products SET specifications = 'Specification|Details\n---|---\nCapacity|32GB (2 x 16GB)\nMemory Type|DDR5\nSpeed|5600MHz\nTested Latency|36-36-36-76\nVoltage|1.25V\nFormat|DIMM\nPin Out|288-Pin\nHeatspreader|Anodized Aluminum\nCompatibility|Intel 600 Series, Intel 700 Series\nXMP Profile|XMP 3.0' WHERE product_name = 'Corsair Vengeance 32GB DDR5';

UPDATE products SET specifications = 'Specification|Details\n---|---\nCapacity|32GB (2 x 16GB)\nMemory Type|DDR5\nSpeed|6000MHz\nTested Latency|CL40\nVoltage|1.35V\nFormat|DIMM\nPin Out|288-Pin\nHeatspreader|Aluminum\nCompatibility|Intel 600 Series, Intel 700 Series\nXMP Profile|XMP 3.0 Certified' WHERE product_name = 'Kingston Fury Beast 32GB DDR5';

UPDATE products SET specifications = 'Specification|Details\n---|---\nCapacity|2TB\nForm Factor|M.2 (2280)\nInterface|PCIe Gen 4.0 x4, NVMe 1.3c\nController|Samsung Elpis Controller\nNAND Flash|Samsung V-NAND 3-bit MLC\nDRAM Cache|2GB LPDDR4\nSequential Read|Up to 7,000 MB/s\nSequential Write|Up to 5,100 MB/s\nRandom Read (4KB, QD32)|Up to 1,000,000 IOPS\nRandom Write (4KB, QD32)|Up to 1,000,000 IOPS\nEndurance (TBW)|1,200 TBW' WHERE product_name = 'Samsung 980 Pro 2TB NVMe SSD';

UPDATE products SET specifications = 'Specification|Details\n---|---\nWeight|<63 g\nSensor|HERO™ 25K\nResolution|100 – 25,600 DPI\nMax. acceleration|> 40G\nMax. speed|> 400 IPS\nWireless technology|LIGHTSPEED Wireless\nReport Rate|1000 Hz (1ms)\nBattery Life|Constant motion: 70h\nFeet|Large, zero-additive PTFE\nButtons|5' WHERE product_name = 'Logitech G Pro X Superlight';

UPDATE products SET specifications = 'Specification|Details\n---|---\nTotal Cores|14\n# of Performance-cores|6\n# of Efficient-cores|8\nTotal Threads|20\nMax Turbo Frequency|5.10 GHz\nPerformance-core Max Turbo Frequency|5.10 GHz\nEfficient-core Max Turbo Frequency|3.90 GHz\nCache|24 MB Intel® Smart Cache\nTotal L2 Cache|20 MB\nProcessor Base Power|125 W\nMaximum Turbo Power|181 W\nMemory Types|Up to DDR5 5600 MT/s, Up to DDR4 3200 MT/s\nMax # of Memory Channels|2\nPCI Express Revision|5.0 and 4.0\nSockets Supported|FCLGA1700' WHERE product_name = 'Intel Core i5-13600K';

UPDATE products SET specifications = 'Specification|Details\n---|---\nCPU Cores|8\nCPU Threads|16\nBase Clock|4.5GHz\nMax Boost Clock|Up to 5.4GHz\nTotal L1 Cache|512KB\nTotal L2 Cache|8MB\nTotal L3 Cache|32MB\nUnlocked for Overclocking|Yes\nCMOS|TSMC 5nm FinFET\nPackage|AM5\nPCI Express® Version|PCIe 5.0\nIntegrated Graphics|AMD Radeon™ Graphics\nDefault TDP|105W' WHERE product_name = 'AMD Ryzen 7 7700X';

UPDATE products SET specifications = 'Specification|Details\n---|---\nGPU Engine|Ada Lovelace\nCUDA Cores|9728\nBoost Clock|2.51 GHz\nStandard Memory Config|16 GB GDDR6X\nMemory Interface Width|256-bit\nRay Tracing Cores|3rd Generation\nTensor Cores|4th Generation\nNVIDIA DLSS|3.0\nPCI Express|Gen 4\nOutputs|1x HDMI, 3x DisplayPort\nPower Connectors|1x 16-pin (12VHPWR)\nRecommended PSU|750W' WHERE product_name = 'NVIDIA GeForce RTX 4080';

UPDATE products SET specifications = 'Specification|Details\n---|---\nArchitecture|AMD RDNA™ 3\nStream Processors|5376\nCompute Units|84\nRay Accelerators|84\nGame Clock|2.0 GHz\nBoost Clock|Up to 2.4 GHz\nMemory Size|20 GB GDDR6\nMemory Interface|320-bit\nInfinity Cache|80MB (2nd Gen)\nDisplayPort|2.1\nHDMI|2.1a\nPower Connectors|2x 8-pin\nRecommended PSU|750W' WHERE product_name = 'AMD Radeon RX 7900 XT';

UPDATE products SET specifications = 'Specification|Details\n---|---\nChipset|AMD B650E\nCPU Socket|AM5\nForm Factor|ATX\nPower Stages|12+2 (80A)\nMemory Support|4x DIMM, Max. 128GB, DDR5\nMax Memory Speed|6400+(OC)\nExpansion Slots|1x PCIe 5.0 x16, 2x PCIe 4.0 x1, 1x PCIe 4.0 x16 (x4 mode)\nStorage|1x M.2 PCIe 5.0, 2x M.2 PCIe 4.0, 4x SATA 6Gb/s\nNetworking|Intel® 2.5Gb Ethernet, Wi-Fi 6E\nAudio|ROG SupremeFX ALC4080\nRear I/O|DisplayPort, HDMI, 1x USB-C 3.2 Gen 2x2, 3x USB 3.2 Gen 2, 4x USB 2.0, Wi-Fi 6E, 2.5Gb LAN, BIOS FlashBack™' WHERE product_name = 'ASUS ROG Strix B650E-F';

UPDATE products SET specifications = 'Specification|Details\n---|---\nChipset|AMD B550\nCPU Socket|AM4\nForm Factor|ATX\nVRM|10+2+1 Duet Rail Power System\nMemory Support|4x DIMM, Max. 128GB, DDR4\nMax Memory Speed|5100+(OC)\nExpansion Slots|1x PCIe 4.0 x16, 1x PCIe 3.0 x16 (x4), 2x PCIe 3.0 x1\nStorage|1x M.2 PCIe 4.0, 1x M.2 PCIe 3.0, 6x SATA 6Gb/s\nNetworking|Realtek® 2.5Gb LAN, Intel® Wi-Fi 6 AX200\nAudio|Realtek® ALC1200 Codec\nRear I/O|DisplayPort, HDMI, 2x USB 3.2 Gen 2, 2x USB 3.2 Gen 1, 2x USB 2.0, Wi-Fi 6, 2.5Gb LAN, Flash BIOS Button' WHERE product_name = 'MSI MPG B550 Gaming Edge';

UPDATE products SET specifications = 'Specification|Details\n---|---\nCapacity|32GB (2 x 16GB)\nMemory Type|DDR5\nSpeed|6200MHz\nTested Latency|36-36-36-76\nVoltage|1.35V\nFormat|DIMM\nPin Out|288-Pin\nHeatspreader|Forged Aluminum\nCompatibility|Intel 600 Series, Intel 700 Series\nXMP Profile|XMP 3.0' WHERE product_name = 'Corsair Dominator Platinum 32GB DDR5';

UPDATE products SET specifications = 'Specification|Details\n---|---\nCapacity|2TB\nForm Factor|M.2 (2280)\nInterface|PCIe Gen 4.0 x4, NVMe 2.0\nController|Phison E18\nNAND Flash|3D TLC\nSequential Read|Up to 7,300 MB/s\nSequential Write|Up to 7,000 MB/s\nRandom Read (4K)|Up to 1,000,000 IOPS\nRandom Write (4K)|Up to 1,000,000 IOPS\nEndurance (TBW)|2000TB' WHERE product_name = 'Kingston Renegade 2TB NVMe SSD';

UPDATE products SET specifications = 'Specification|Details\n---|---\nSwitch Type|Low Profile GL Tactile\nActuation distance|1.5 mm\nActuation force|50 g\nTotal travel distance|2.7 mm\nConnectivity|LIGHTSPEED Wireless, Bluetooth\nBattery Life (RGB)|40 hours\nOnboard Memory|2 Lighting Profiles, 3 Macro Profiles\nDimensions|368mm x 150mm x 22mm\nWeight|810 g' WHERE product_name = 'Logitech G915 TKL Keyboard';
